/**
 * Standardized response codes for API responses
 * Format: {CATEGORY}_{DESCRIPTION}
 * This allows frontend to handle specific errors without parsing messages
 */

export const RESPONSE_CODES = {
  // ============================================
  // SUCCESS CODES (2xx)
  // ============================================
  SUCCESS: 'SUCCESS',
  CREATED: 'RESOURCE_CREATED',
  UPDATED: 'RESOURCE_UPDATED',
  DELETED: 'RESOURCE_DELETED',
  NO_CONTENT: 'NO_CONTENT',

  // ============================================
  // CLIENT ERROR CODES (4xx)
  // ============================================

  // General Client Errors
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'RESOURCE_NOT_FOUND',
  CONFLICT: 'RESOURCE_CONFLICT',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  TOO_MANY_REQUESTS: 'RATE_LIMIT_EXCEEDED',

  // Authentication Errors
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_BLACKLISTED: 'AUTH_TOKEN_BLACKLISTED',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_PASSWORD_INCORRECT: 'AUTH_PASSWORD_INCORRECT',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',

  // User Errors
  USER_EMAIL_EXISTS: 'USER_EMAIL_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_CANNOT_DELETE_SELF: 'USER_CANNOT_DELETE_SELF',
  USER_CANNOT_DELETE_LAST_ADMIN: 'USER_CANNOT_DELETE_LAST_ADMIN',
  USER_INACTIVE: 'USER_INACTIVE',

  // Role Errors
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_SLUG_EXISTS: 'ROLE_SLUG_EXISTS',
  ROLE_NAME_EXISTS: 'ROLE_NAME_EXISTS',
  ROLE_IN_USE: 'ROLE_IN_USE',
  ROLE_CANNOT_DELETE_SYSTEM: 'ROLE_CANNOT_DELETE_SYSTEM',
  ROLE_INACTIVE: 'ROLE_INACTIVE',
  ROLE_INVALID: 'ROLE_INVALID',

  // Product Errors
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_SKU_EXISTS: 'PRODUCT_SKU_EXISTS',
  PRODUCT_SLUG_EXISTS: 'PRODUCT_SLUG_EXISTS',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',
  PRODUCT_INSUFFICIENT_STOCK: 'PRODUCT_INSUFFICIENT_STOCK',
  PRODUCT_INACTIVE: 'PRODUCT_INACTIVE',

  // Customer Errors
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_EMAIL_EXISTS: 'CUSTOMER_EMAIL_EXISTS',
  CUSTOMER_HAS_ORDERS: 'CUSTOMER_HAS_ORDERS',
  CUSTOMER_INSUFFICIENT_POINTS: 'CUSTOMER_INSUFFICIENT_POINTS',

  // Order Errors
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_STATUS: 'ORDER_INVALID_STATUS',
  ORDER_ALREADY_CONFIRMED: 'ORDER_ALREADY_CONFIRMED',
  ORDER_CANNOT_CANCEL: 'ORDER_CANNOT_CANCEL',
  ORDER_CANNOT_UPDATE: 'ORDER_CANNOT_UPDATE',
  ORDER_EMPTY_CART: 'ORDER_EMPTY_CART',

  // Category Errors
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_SLUG_EXISTS: 'CATEGORY_SLUG_EXISTS',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',
  CATEGORY_HAS_CHILDREN: 'CATEGORY_HAS_CHILDREN',
  CATEGORY_CIRCULAR_REFERENCE: 'CATEGORY_CIRCULAR_REFERENCE',

  // Order Errors

  ORDER_ALREADY_CANCELLED: 'ORDER_ALREADY_CANCELLED',
  ORDER_ALREADY_COMPLETED: 'ORDER_ALREADY_COMPLETED',

  // Customer Errors
  CUSTOMER_INACTIVE: 'CUSTOMER_INACTIVE',

  // Inventory Errors
  INVENTORY_NOT_FOUND: 'INVENTORY_NOT_FOUND',
  INVENTORY_INSUFFICIENT_STOCK: 'INVENTORY_INSUFFICIENT_STOCK',
  INVENTORY_INVALID_QUANTITY: 'INVENTORY_INVALID_QUANTITY',

  // Discount Errors
  DISCOUNT_NOT_FOUND: 'DISCOUNT_NOT_FOUND',
  DISCOUNT_CODE_EXISTS: 'DISCOUNT_CODE_EXISTS',
  DISCOUNT_INVALID_VALUE: 'DISCOUNT_INVALID_VALUE',
  DISCOUNT_EXPIRED: 'DISCOUNT_EXPIRED',
  DISCOUNT_NOT_STARTED: 'DISCOUNT_NOT_STARTED',
  DISCOUNT_USAGE_LIMIT_REACHED: 'DISCOUNT_USAGE_LIMIT_REACHED',
  DISCOUNT_MIN_ORDER_NOT_MET: 'DISCOUNT_MIN_ORDER_NOT_MET',

  // Media/File Errors
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
  MEDIA_NO_FILE: 'MEDIA_NO_FILE',
  MEDIA_UPLOAD_FAILED: 'MEDIA_UPLOAD_FAILED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_INVALID_TYPE: 'FILE_INVALID_TYPE',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',

  // ============================================
  // SERVER ERROR CODES (5xx)
  // ============================================
  INTERNAL_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  REDIS_ERROR: 'REDIS_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
} as const;

export type ResponseCode = (typeof RESPONSE_CODES)[keyof typeof RESPONSE_CODES];

/**
 * Map HTTP status codes to default response codes
 */
export const HTTP_TO_RESPONSE_CODE: Record<number, ResponseCode> = {
  200: RESPONSE_CODES.SUCCESS,
  201: RESPONSE_CODES.CREATED,
  204: RESPONSE_CODES.NO_CONTENT,
  400: RESPONSE_CODES.BAD_REQUEST,
  401: RESPONSE_CODES.UNAUTHORIZED,
  403: RESPONSE_CODES.FORBIDDEN,
  404: RESPONSE_CODES.NOT_FOUND,
  409: RESPONSE_CODES.CONFLICT,
  422: RESPONSE_CODES.VALIDATION_ERROR,
  429: RESPONSE_CODES.TOO_MANY_REQUESTS,
  500: RESPONSE_CODES.INTERNAL_ERROR,
  503: RESPONSE_CODES.SERVICE_UNAVAILABLE,
};
